/**
 * ~200 common 5-letter words used as the answer pool.
 * Everyone gets the same daily word (date-based index).
 */
export const ANSWERS: string[] = [
  "about", "above", "abuse", "actor", "acute", "admit", "adopt", "adult", "after", "again",
  "agent", "agree", "ahead", "alarm", "album", "alert", "alien", "align", "alike", "alive",
  "allow", "alone", "along", "alter", "ample", "angel", "anger", "angle", "angry", "anime",
  "ankle", "apple", "apply", "arena", "argue", "arise", "armor", "array", "aside", "asset",
  "avoid", "award", "aware", "badge", "badly", "baker", "basic", "basis", "beach", "begin",
  "being", "below", "bench", "berry", "birth", "black", "blade", "blame", "blank", "blast",
  "blaze", "bleed", "blend", "bless", "blind", "block", "blood", "bloom", "blown", "board",
  "bonus", "boost", "bound", "brain", "brand", "brave", "bread", "break", "breed", "brick",
  "brief", "bring", "broad", "broke", "brook", "brown", "brush", "build", "bunch", "burst",
  "buyer", "cabin", "candy", "carry", "catch", "cause", "chain", "chair", "charm", "chase",
  "cheap", "check", "cheek", "chess", "chest", "chief", "child", "chill", "claim", "clash",
  "class", "clean", "clear", "climb", "cling", "clock", "close", "cloth", "cloud", "coach",
  "coast", "could", "count", "court", "cover", "crack", "craft", "crane", "crash", "crazy",
  "cream", "crime", "cross", "crowd", "crown", "crush", "curve", "cycle", "daily", "dance",
  "death", "debut", "delay", "depth", "devil", "dirty", "doubt", "dozen", "draft", "drain",
  "drama", "drank", "drawn", "dream", "dress", "drift", "drink", "drive", "drove", "dying",
  "eager", "early", "earth", "eight", "elder", "elite", "empty", "enemy", "enjoy", "enter",
  "entry", "equal", "error", "essay", "event", "every", "exact", "exert", "exist", "extra",
  "faint", "faith", "false", "fancy", "fatal", "fault", "feast", "fence", "fever", "fiber",
  "field", "fight", "final", "first", "fixed", "flame", "flash", "fleet", "flesh", "float",
  "flood", "floor", "flora", "fluid", "flush", "flute", "focus", "force", "forge", "forth",
  "forum", "found", "frame", "frank", "fraud", "fresh", "front", "frost", "fruit", "fungi",
];

/**
 * ~2000 valid guess words (superset of answers).
 * Includes all answers plus additional common 5-letter words.
 */
export const VALID_GUESSES: Set<string> = new Set([
  ...ANSWERS,
  "aback", "abate", "abbey", "abbot", "abide", "abort", "abyss", "acorn", "acrid", "adapt",
  "adept", "adore", "adorn", "aegis", "afoot", "afoul", "agape", "agate", "agile", "aging",
  "aglow", "agony", "aisle", "alibi", "allay", "alley", "allot", "aloft", "aloof", "alpha",
  "amass", "amaze", "amber", "amble", "amend", "amine", "amino", "amiss", "amity", "among",
  "ample", "amuse", "angel", "annex", "annoy", "antic", "anvil", "aorta", "apart", "aphid",
  "aping", "apnea", "appel", "areal", "argon", "aroma", "arrow", "arson", "artsy", "ashen",
  "aster", "atoll", "atone", "attic", "audio", "audit", "augur", "aunty", "avian", "avocl",
  "await", "awake", "awash", "awful", "awoke", "axial", "axiom", "azure", "bacon", "badge",
  "badly", "bagel", "baggy", "balmy", "banal", "banjo", "barge", "baron", "basal", "basin",
  "batch", "batty", "bayou", "beard", "beast", "began", "begot", "beige", "belle", "belly",
  "belts", "berth", "beset", "betel", "bevel", "bible", "bicep", "biddy", "bight", "billy",
  "binge", "biome", "birch", "bison", "bitty", "blare", "blase", "blaze", "bleak", "bleat",
  "bleed", "blimp", "bliss", "blitz", "bloat", "bloke", "blond", "bloom", "blown", "blues",
  "bluff", "blunt", "blurt", "blush", "bogey", "bogus", "bolts", "bones", "books", "boost",
  "booty", "booze", "borax", "borne", "bosom", "bossy", "botch", "bound", "bough", "bowel",
  "boxer", "brace", "braid", "brake", "brash", "brass", "brawl", "brawn", "bread", "briar",
  "bribe", "bride", "brine", "brink", "briny", "brisk", "broil", "brood", "brook", "broth",
  "brush", "brunt", "budge", "buggy", "bulge", "bulky", "bully", "bunch", "bunny", "burly",
  "burnt", "burro", "burst", "butch", "buyer", "bylaw", "cabal", "cabin", "cache", "cadet",
  "camel", "cameo", "candy", "canny", "canoe", "caper", "carat", "cargo", "carol", "carry",
  "carve", "catch", "cater", "cause", "cedar", "chain", "chalk", "champ", "chant", "chaos",
  "chard", "charm", "chart", "chase", "cheap", "cheat", "cheek", "cheer", "chess", "chest",
  "chick", "chief", "child", "chili", "chill", "chime", "china", "chirp", "choir", "chord",
  "chore", "chose", "chunk", "churn", "cider", "cigar", "cinch", "circa", "cisco", "civic",
  "civil", "claim", "clamp", "clang", "clank", "clash", "clasp", "class", "claws", "clean",
  "clear", "clerk", "click", "cliff", "climb", "cline", "cling", "cloak", "clock", "clone",
  "close", "cloth", "cloud", "clout", "clown", "clubs", "cluck", "clued", "clump", "clung",
  "coach", "coals", "coast", "cobra", "cocoa", "colon", "color", "comet", "comic", "comma",
  "conch", "coral", "corny", "couch", "cough", "could", "count", "coupe", "court", "cover",
  "covet", "crack", "craft", "cramp", "crane", "crank", "crash", "crass", "crate", "crave",
  "crawl", "craze", "crazy", "creak", "cream", "creed", "creek", "creep", "crest", "crews",
  "crime", "crimp", "crisp", "croak", "crock", "crone", "crook", "crops", "cross", "crowd",
  "crown", "crude", "cruel", "crush", "crust", "crypt", "cubic", "cumin", "cupid", "curly",
  "curry", "curse", "curve", "cycle", "cynic", "daddy", "daily", "dairy", "daisy", "dance",
  "dandy", "dated", "dealt", "death", "debit", "debug", "debut", "decal", "decay", "decor",
  "decoy", "decry", "defer", "deign", "deity", "delay", "delta", "delve", "demon", "demur",
  "denim", "dense", "depot", "depth", "derby", "deter", "detox", "deuce", "devil", "devot",
  "diary", "dicey", "digit", "diner", "dingy", "dirty", "disco", "ditch", "ditto", "ditty",
  "diver", "dizzy", "dodge", "dogma", "doing", "dolly", "donor", "donut", "doubt", "dough",
  "dowdy", "dowel", "downs", "dozed", "dozen", "draft", "drain", "drake", "drape", "dread",
  "dream", "dress", "dried", "drift", "drill", "drink", "drive", "droit", "droll", "drone",
  "drool", "droop", "drove", "drown", "drugs", "drums", "drunk", "dryer", "dryly", "ducky",
  "dumpy", "dunce", "duple", "dusty", "dutch", "duvet", "dwarf", "dwell", "dying", "eager",
  "eagle", "early", "earth", "easel", "eaten", "eater", "eaves", "ebony", "edged", "edict",
  "eight", "elbow", "elder", "elect", "elfin", "elite", "elope", "elude", "email", "embed",
  "ember", "emcee", "empty", "enact", "endow", "enemy", "enjoy", "ennui", "ensue", "enter",
  "entry", "envoy", "epoch", "epoxy", "equal", "equip", "erase", "erode", "error", "erupt",
  "essay", "ether", "ethic", "evade", "event", "every", "evict", "evoke", "exact", "exalt",
  "exams", "excel", "exert", "exile", "exist", "expat", "expel", "extra", "exude", "exult",
  "eyrie", "fable", "facet", "faint", "fairy", "faith", "false", "fancy", "fatal", "fatty",
  "fault", "fauna", "feast", "feign", "feint", "fella", "felon", "femur", "fence", "ferry",
  "fetal", "fetch", "fever", "fewer", "fiber", "fibre", "field", "fiend", "fifth", "fifty",
  "fight", "filer", "filth", "final", "finch", "first", "fishy", "fitly", "fixer", "fizzy",
  "fjord", "flack", "flair", "flake", "flaky", "flame", "flank", "flaps", "flare", "flash",
  "flask", "flesh", "flick", "flier", "fling", "flint", "float", "flock", "flood", "floor",
  "flora", "floss", "flour", "flout", "flown", "fluid", "fluke", "flung", "flunk", "flush",
  "flute", "focal", "focus", "foggy", "folly", "force", "forge", "forgo", "forte", "forth",
  "forty", "forum", "fossil","found", "foxed", "foyer", "frail", "frame", "frank", "fraud",
  "freak", "freed", "fresh", "friar", "fried", "frill", "frisk", "front", "frost", "froze",
  "fruit", "frump", "fungi", "funky", "funny", "furry", "fussy", "fuzzy", "gaffe", "gamma",
  "gaudy", "gauge", "gaunt", "gauze", "gavel", "giddy", "given", "gizmo", "gland", "glare",
  "glass", "gleam", "glean", "glide", "glint", "gloat", "globe", "gloom", "gloss", "glove",
  "glyph", "gnarly","gnash", "goats", "going", "golem", "golly", "goose", "gorge", "gouge",
  "gourd", "grace", "grade", "graft", "grail", "grain", "grand", "grant", "grape", "graph",
  "grasp", "grass", "grate", "grave", "gravy", "great", "greed", "green", "greet", "grief",
  "grill", "grime", "grind", "gripe", "groan", "groin", "groom", "grope", "gross", "group",
  "grout", "grove", "growl", "grown", "gruel", "gruff", "grunt", "guava", "guess", "guest",
  "guide", "guild", "guilt", "guise", "gulch", "gully", "gumbo", "gummy", "guppy", "gusto",
  "gusty", "gypsy", "habit", "hairy", "halve", "handy", "happy", "hardy", "haste", "hasty",
  "hatch", "haunt", "haven", "havoc", "hazel", "heady", "heart", "heave", "heavy", "hedge",
  "hefty", "heist", "helix", "hello", "hence", "herbs", "heron", "hilly", "hinge", "hippo",
  "hitch", "hoard", "hobby", "homer", "honey", "honor", "horse", "hotel", "hound", "house",
  "hover", "howdy", "human", "humid", "humps", "humus", "hurry", "hyena", "hyper", "icing",
  "ideal", "idiom", "idiot", "image", "imbue", "impel", "imply", "inane", "incur", "index",
  "inept", "inert", "infer", "ingot", "inner", "input", "inter", "intro", "ionic", "irate",
  "ivory", "jaunt", "jazzy", "jelly", "jewel", "jiffy", "joker", "joust", "judge", "juice",
  "juicy", "jumbo", "jumpy", "junco", "juror", "karma", "kayak", "kebab", "khaki", "kinky",
  "knack", "knead", "kneel", "knelt", "knife", "knobs", "knock", "knoll", "knots", "known",
  "koala", "kudos", "label", "labor", "laden", "ladle", "lager", "lance", "lapel", "lapse",
  "large", "larva", "laser", "latch", "later", "lathe", "latte", "laugh", "layer", "leach",
  "leafy", "leaky", "leapt", "learn", "lease", "leash", "least", "leave", "ledge", "leggy",
  "lemon", "lemur", "level", "lever", "libel", "light", "liken", "lilac", "limbo", "limit",
  "linen", "liner", "lingo", "links", "lions", "liter", "litre", "livid", "llama", "lodge",
  "lofty", "logic", "login", "loopy", "loose", "lorry", "loser", "lousy", "lover", "lower",
  "loyal", "lucid", "lucky", "lumen", "lunar", "lunch", "lunge", "lurch", "lusty", "lying",
  "lynch", "lyric", "macho", "macro", "mafia", "magic", "magma", "major", "maker", "manga",
  "mango", "manly", "manor", "maple", "march", "marry", "marsh", "mason", "match", "mayor",
  "mealy", "meant", "media", "medic", "melee", "melon", "mercy", "merge", "merit", "merry",
  "metal", "meter", "midst", "might", "mimic", "mince", "minor", "minus", "mirth", "miser",
  "misty", "mixer", "model", "modem", "mogul", "moist", "molar", "money", "month", "moose",
  "moral", "morph", "mound", "mount", "mourn", "mouse", "mouth", "movie", "muddy", "mulch",
  "mural", "murky", "mushy", "music", "musty", "muted", "nadir", "naive", "nanny", "nasal",
  "nasty", "naval", "nerve", "never", "newer", "newly", "niche", "night", "ninja", "noble",
  "noise", "noisy", "north", "notch", "novel", "nudge", "nurse", "nymph", "oaken", "oasis",
  "ocean", "octet", "offal", "offer", "often", "olive", "onset", "opera", "optic", "orbit",
  "order", "organ", "other", "otter", "ought", "ounce", "outer", "outdo", "overt", "ovoid",
  "owing", "owner", "oxide", "ozone", "paddy", "pagan", "paint", "palsy", "panel", "panic",
  "pansy", "paper", "party", "pasta", "paste", "patch", "patio", "pause", "peach", "pearl",
  "pecan", "pedal", "penal", "pence", "penny", "perch", "peril", "perky", "pesky", "petal",
  "petty", "phase", "phone", "photo", "piano", "piece", "piggy", "pilot", "pinch", "pious",
  "pixel", "pizza", "place", "plaid", "plain", "plait", "plane", "plank", "plant", "plate",
  "plaza", "plead", "pleat", "plied", "plier", "pluck", "plumb", "plume", "plump", "plunk",
  "plush", "plying","point", "poise", "poker", "polar", "polka", "polyp", "poppy", "porch",
  "poser", "posse", "pouch", "pound", "pouty", "power", "prank", "prawn", "press", "price",
  "pride", "pried", "prime", "print", "prior", "prism", "privy", "prize", "probe", "prone",
  "proof", "prose", "proud", "prove", "prowl", "prude", "prune", "psalm", "pubic", "pudgy",
  "pulse", "punch", "pupil", "puppy", "purge", "purse", "pushy", "putty", "pygmy", "qualm",
  "quart", "quasi", "queen", "query", "quest", "queue", "quick", "quiet", "quill", "quirk",
  "quota", "quote", "rabbi", "radar", "radio", "rainy", "raise", "rally", "ranch", "range",
  "rapid", "ratio", "raven", "reach", "realm", "rebel", "rebus", "recap", "recur", "refer",
  "reign", "relax", "relay", "remit", "renew", "repay", "repel", "reply", "rerun", "reset",
  "resin", "retro", "retry", "reuse", "revel", "rider", "ridge", "rifle", "rigid", "rigor",
  "rinse", "risen", "risky", "rival", "river", "rivet", "robin", "robot", "rocky", "rogue",
  "roost", "rouge", "round", "route", "rover", "rowdy", "royal", "rugby", "ruins", "ruler",
  "rumba", "rumor", "rupee", "rural", "rusty", "sadly", "saint", "salad", "salon", "salsa",
  "salty", "salve", "sandy", "saucy", "sauna", "savor", "savvy", "scale", "scalp", "scaly",
  "scamp", "scant", "scare", "scarf", "scary", "scene", "scent", "score", "scorn", "scout",
  "scowl", "scram", "scrap", "scree", "screw", "scrub", "sedan", "seize", "sense", "sepia",
  "serve", "setup", "seven", "sever", "shade", "shady", "shaft", "shake", "shaky", "shall",
  "shame", "shape", "shard", "share", "shark", "sharp", "shawl", "shear", "sheen", "sheep",
  "sheer", "sheet", "shelf", "shell", "shift", "shine", "shiny", "shire", "shirt", "shock",
  "shore", "short", "shout", "shove", "shown", "shrub", "shrug", "shuck", "shunt", "siege",
  "sight", "sigma", "silly", "since", "siren", "sixty", "skate", "skimp", "skull", "skunk",
  "slack", "slain", "slang", "slant", "slash", "slate", "sleek", "sleep", "sleet", "slept",
  "slice", "slide", "slime", "slimy", "sling", "slink", "slope", "sloth", "slump", "slung",
  "slunk", "slurp", "smart", "smash", "smear", "smell", "smelt", "smile", "smite", "smith",
  "smock", "smoke", "smoky", "snack", "snail", "snake", "snare", "snark", "snarl", "sneak",
  "sneer", "snide", "sniff", "snore", "snort", "snout", "snowy", "sober", "solar", "solid",
  "solve", "sonic", "sorry", "sound", "south", "space", "spade", "spare", "spark", "spawn",
  "speak", "spear", "speed", "spell", "spend", "spent", "spice", "spicy", "spied", "spike",
  "spill", "spine", "spoke", "spoof", "spook", "spool", "spoon", "sport", "spray", "spree",
  "sprig", "spunk", "squat", "squid", "staff", "stage", "stain", "stair", "stake", "stale",
  "stalk", "stall", "stamp", "stand", "stank", "stare", "stark", "start", "stash", "state",
  "stays", "steak", "steal", "steam", "steel", "steep", "steer", "stern", "stick", "stiff",
  "still", "sting", "stink", "stint", "stock", "stoic", "stoke", "stole", "stomp", "stone",
  "stony", "stood", "stool", "stoop", "store", "stork", "storm", "story", "stout", "stove",
  "strap", "straw", "stray", "strip", "strut", "stuck", "stuff", "stump", "stung", "stunk",
  "stunt", "style", "suave", "sugar", "suite", "sulky", "sunny", "super", "surge", "sushi",
  "swamp", "swarm", "swear", "sweat", "sweep", "sweet", "swell", "swept", "swift", "swill",
  "swine", "swing", "swipe", "swirl", "sword", "swore", "sworn", "swung", "syrup", "tabby",
  "table", "tacit", "taffy", "taint", "taken", "tally", "talon", "tango", "tangy", "taper",
  "tapir", "tardy", "taste", "tasty", "taunt", "tawny", "teach", "teeth", "tempo", "tense",
  "tenth", "tepid", "theme", "thick", "thief", "thigh", "thing", "think", "third", "thorn",
  "those", "three", "threw", "throw", "thrum", "thumb", "thump", "tiara", "tidal", "tiger",
  "tight", "timer", "timid", "tipsy", "titan", "title", "toast", "today", "token", "topic",
  "torch", "total", "totem", "touch", "tough", "towel", "tower", "toxic", "trace", "track",
  "trade", "trail", "train", "trait", "tramp", "trash", "trawl", "treat", "trend", "triad",
  "trial", "tribe", "trick", "tried", "trill", "tripe", "trite", "troll", "troop", "trout",
  "trove", "truce", "truck", "truly", "trump", "trunk", "truss", "trust", "truth", "tulip",
  "tumor", "tuner", "tunic", "turbo", "tutor", "twang", "tweak", "tweed", "tweet", "twice",
  "twigs", "twine", "twist", "tying", "udder", "ulcer", "ultra", "umbra", "uncle", "uncut",
  "under", "undid", "undue", "unfit", "unify", "union", "unite", "unity", "unlit", "until",
  "unwed", "upper", "upset", "urban", "usage", "usher", "using", "usual", "usurp", "utile",
  "utter", "valid", "valor", "value", "valve", "vapor", "vault", "vegan", "venue", "verge",
  "verse", "vigor", "vinyl", "viola", "viper", "viral", "virus", "visor", "visit", "vista",
  "vital", "vivid", "vocal", "vodka", "vogue", "voice", "voila", "voter", "vouch", "vowel",
  "vulva", "wafer", "wager", "wagon", "watch", "water", "weary", "weave", "wedge", "weird",
  "whale", "wheat", "wheel", "where", "which", "while", "whiff", "whine", "whirl", "white",
  "whole", "whose", "wield", "wince", "windy", "witch", "wispy", "woman", "woods", "world",
  "worry", "worse", "worst", "worth", "would", "wound", "wrath", "wreak", "wreck", "wring",
  "wrist", "write", "wrong", "wrote", "yacht", "yearn", "yeast", "yield", "young", "youth",
  "zebra", "zesty",
]);

/** Get today's answer word (same for everyone on the same day). */
export function getTodaysWord(): string {
  const epoch = new Date(2024, 0, 1); // Jan 1 2024
  const today = new Date();
  const daysSinceEpoch = Math.floor(
    (today.getTime() - epoch.getTime()) / (1000 * 60 * 60 * 24),
  );
  return ANSWERS[daysSinceEpoch % ANSWERS.length]!;
}

/** Get a random answer word (for practice mode). */
export function getRandomWord(): string {
  return ANSWERS[Math.floor(Math.random() * ANSWERS.length)]!;
}

/** Check if a guess is a valid 5-letter word. */
export function isValidGuess(word: string): boolean {
  return VALID_GUESSES.has(word.toLowerCase());
}
